server:
  port: 9192
spring:
  application:
    name: studentApp
  datasource:
    username: avnadmin
    password: ${DB_PASSWORD}
    url: jdbc:mysql://mysql-lyspaul-project1-lp.g.aivencloud.com:13917/student_app
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true


    database-platform: org.hibernate.dialect.MySQL8Dialect


