server:
  port: 9192
spring:
  application:
    name: studentApp
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3307/student_app
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true


    database-platform: org.hibernate.dialect.MySQL8Dialect


